
-- World Database

-- Easy
-- 1. Find the names of all the countries in the database.
SELECT Name FROM country;

-- 2. List all the cities in the city table from the country 'USA'.
SELECT Name FROM city WHERE CountryCode = 'USA';

-- 3. Retrieve the population and life expectancy for all countries in descending order of life expectancy.
SELECT Name, Population, LifeExpectancy FROM country ORDER BY LifeExpectancy DESC;

-- Intermediate
-- 4. Find the total population of all countries in the region 'Eastern Europe'.
SELECT SUM(Population) FROM country WHERE Region = 'Eastern Europe';

-- 5. List all cities with a population greater than 1 million, sorted by population in descending order.
SELECT Name, Population FROM city WHERE Population > 1000000 ORDER BY Population DESC;

-- 6. Find the names of all countries where the official language is 'Spanish'.
SELECT country.Name FROM country
JOIN countrylanguage ON country.Code = countrylanguage.CountryCode
WHERE countrylanguage.Language = 'Spanish' AND countrylanguage.IsOfficial = 'T';

-- Hard
-- 7. List the top 5 most populated cities in each continent.
SELECT city.Name, country.Continent, city.Population
FROM city
JOIN country ON city.CountryCode = country.Code
WHERE city.Population IN (
    SELECT Population FROM city WHERE CountryCode = country.Code ORDER BY Population DESC LIMIT 5
)
ORDER BY country.Continent, city.Population DESC;

-- 8. Find the country with the highest life expectancy in each region.
SELECT Name, Region, LifeExpectancy
FROM country c1
WHERE LifeExpectancy = (
    SELECT MAX(LifeExpectancy)
    FROM country c2
    WHERE c2.Region = c1.Region
);

-- 9. Calculate the average population of countries where more than 50% of the people speak an official language.
SELECT AVG(Population)
FROM country
WHERE Code IN (
    SELECT CountryCode FROM countrylanguage WHERE Percentage > 50 AND IsOfficial = 'T'
);

-- Chinook Database

-- Easy
-- 1. List all the tracks from the album 'Let There Be Rock'.
SELECT TrackId, Name FROM Track WHERE AlbumId = (SELECT AlbumId FROM Album WHERE Title = 'Let There Be Rock');

-- 2. Find the name and email of all customers.
SELECT FirstName, LastName, Email FROM Customer;

-- 3. Retrieve the names of all playlists in the database.
SELECT Name FROM Playlist;

-- Intermediate
-- 4. List the names of all artists who have albums in the database.
SELECT DISTINCT Artist.Name FROM Artist
JOIN Album ON Artist.ArtistId = Album.ArtistId;

-- 5. Find the number of tracks in each playlist.
SELECT Playlist.Name, COUNT(PlaylistTrack.TrackId) AS TrackCount
FROM Playlist
JOIN PlaylistTrack ON Playlist.PlaylistId = PlaylistTrack.PlaylistId
GROUP BY Playlist.Name;

-- 6. Find all employees who report to 'Andrew Adams'.
SELECT FirstName, LastName FROM Employee WHERE ReportsTo = (SELECT EmployeeId FROM Employee WHERE FirstName = 'Andrew' AND LastName = 'Adams');

-- Hard
-- 7. Find the top 5 best-selling tracks based on total invoice amount.
SELECT Track.Name, SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalSales
FROM InvoiceLine
JOIN Track ON InvoiceLine.TrackId = Track.TrackId
GROUP BY Track.Name
ORDER BY TotalSales DESC
LIMIT 5;

-- 8. Find the artist with the most albums in the database.
SELECT Artist.Name, COUNT(Album.AlbumId) AS AlbumCount
FROM Artist
JOIN Album ON Artist.ArtistId = Album.ArtistId
GROUP BY Artist.Name
ORDER BY AlbumCount DESC
LIMIT 1;

-- 9. Find the total revenue generated by each genre.
SELECT Genre.Name, SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS Revenue
FROM InvoiceLine
JOIN Track ON InvoiceLine.TrackId = Track.TrackId
JOIN Genre ON Track.GenreId = Genre.GenreId
GROUP BY Genre.Name
ORDER BY Revenue DESC;
